#!/usr/bin/env python3
"""
bin2c — turn a binary blob into a C array.

Usage: bin2c.py <input> <symbol> [output.c]

Emits to stdout (or output.c) two definitions:
    const unsigned char <symbol>[] = { ... };
    const size_t        <symbol>_len = N;

Deterministic across hosts. The output format is identical to the original
tools/bin2c.c — 12 hex bytes per row, lower-case, NUL-terminated linkage.
"""
from __future__ import annotations

import pathlib
import re
import sys

_SYMBOL_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _format_array(symbol: str, blob: bytes, source: pathlib.Path) -> str:
    out = [
        f"/* Auto-generated by scripts/bin2c.py from {source}. Do not edit. */",
        "#include <stddef.h>",
        "",
        f"const unsigned char {symbol}[] = {{",
    ]
    for offset in range(0, len(blob), 12):
        chunk = blob[offset : offset + 12]
        out.append("    " + "".join(f"0x{b:02x}," for b in chunk))
    out += [
        "};",
        f"const size_t {symbol}_len = {len(blob)};",
        "",
    ]
    return "\n".join(out)


def main() -> None:
    if not 3 <= len(sys.argv) <= 4:
        raise SystemExit(f"usage: {sys.argv[0]} <input> <symbol> [output.c]")

    source = pathlib.Path(sys.argv[1])
    symbol = sys.argv[2]
    output = pathlib.Path(sys.argv[3]) if len(sys.argv) == 4 else None

    if not _SYMBOL_RE.match(symbol):
        raise SystemExit(f"bin2c: invalid C identifier: {symbol}")

    try:
        blob = source.read_bytes()
    except OSError as exc:
        raise SystemExit(f"bin2c: cannot open {source}: {exc}") from exc

    rendered = _format_array(symbol, blob, source)

    if output is None:
        sys.stdout.write(rendered)
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered)


if __name__ == "__main__":
    main()
